### ISSUE TITLE
OpenSUSE stumbling on python3

### ISSUE THREAD

**Issue by dustinmiller** [robertdebock/ansible-role-bootstrap#46]
## Describe the bug
It seems this [risky commit](https://github.com/robertdebock/ansible-role-bootstrap/commit/025fcc14f11a5cdc111181b926507aaf14de5131) is causing some trouble on my OpenSUSE Tumbleweed VM

Switching back to python and python-xml resolves the issue

## Playbook

```
role: ansible-role-bootstrap 
```

## Output

Problem: python3-3.8.2-3.1.x86_64 requires python3-base = 3.8.2, but this requirement cannot be provided\n  not installable providers: python3-base-3.8.2-3.1.x86_64[openSUSE-20200501-0]

## Environment

- Virtualbox, OpenSUSE Tumbleweed, version "20210115"

**Comment by robertdebock** [comment]
The role is tested on `opensuse/leap`, not tumbleweed, sorry.

By the way, this sounds more like a packaging problem than a problem with this role; a dependency is described in the RPM (python3 requires python3-base). The package `python3-base` seems to be missing on opensuse/tumbleweed...

If I remember correctly, the risky commit was decided for because some other role required python3. Can't find the communication about it though, sorry.

Feel free to write a PR that addresses the issue.
